/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CardId = IDL.Text;
export const AnswerOption = IDL.Record({
  'text' : IDL.Text,
  'isCorrect' : IDL.Bool,
  'letter' : IDL.Text,
});
export const SolutionStep = IDL.Record({
  'result' : IDL.Text,
  'description' : IDL.Text,
  'stepNumber' : IDL.Nat,
  'formula' : IDL.Text,
});
export const Timestamp = IDL.Int;
export const SavedCard = IDL.Record({
  'id' : CardId,
  'variationQuestion' : IDL.Text,
  'question' : IDL.Text,
  'answerOptions' : IDL.Vec(AnswerOption),
  'steps' : IDL.Vec(SolutionStep),
  'savedAt' : Timestamp,
  'confidence' : IDL.Nat,
});
export const CardInput = IDL.Record({
  'variationQuestion' : IDL.Text,
  'question' : IDL.Text,
  'answerOptions' : IDL.Vec(AnswerOption),
  'steps' : IDL.Vec(SolutionStep),
  'confidence' : IDL.Nat,
});
export const Variation = IDL.Record({
  'id' : IDL.Text,
  'question' : IDL.Text,
  'correctAnswer' : IDL.Text,
  'answerOptions' : IDL.Vec(AnswerOption),
  'distractors' : IDL.Vec(IDL.Text),
  'steps' : IDL.Vec(SolutionStep),
  'confidence' : IDL.Nat,
  'warningFlag' : IDL.Bool,
});
export const SolverResult = IDL.Record({ 'variations' : IDL.Vec(Variation) });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'deleteCard' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getSavedCards' : IDL.Func([], [IDL.Vec(SavedCard)], ['query']),
  'saveCard' : IDL.Func([CardInput], [IDL.Text], []),
  'solveQuestion' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [SolverResult],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CardId = IDL.Text;
  const AnswerOption = IDL.Record({
    'text' : IDL.Text,
    'isCorrect' : IDL.Bool,
    'letter' : IDL.Text,
  });
  const SolutionStep = IDL.Record({
    'result' : IDL.Text,
    'description' : IDL.Text,
    'stepNumber' : IDL.Nat,
    'formula' : IDL.Text,
  });
  const Timestamp = IDL.Int;
  const SavedCard = IDL.Record({
    'id' : CardId,
    'variationQuestion' : IDL.Text,
    'question' : IDL.Text,
    'answerOptions' : IDL.Vec(AnswerOption),
    'steps' : IDL.Vec(SolutionStep),
    'savedAt' : Timestamp,
    'confidence' : IDL.Nat,
  });
  const CardInput = IDL.Record({
    'variationQuestion' : IDL.Text,
    'question' : IDL.Text,
    'answerOptions' : IDL.Vec(AnswerOption),
    'steps' : IDL.Vec(SolutionStep),
    'confidence' : IDL.Nat,
  });
  const Variation = IDL.Record({
    'id' : IDL.Text,
    'question' : IDL.Text,
    'correctAnswer' : IDL.Text,
    'answerOptions' : IDL.Vec(AnswerOption),
    'distractors' : IDL.Vec(IDL.Text),
    'steps' : IDL.Vec(SolutionStep),
    'confidence' : IDL.Nat,
    'warningFlag' : IDL.Bool,
  });
  const SolverResult = IDL.Record({ 'variations' : IDL.Vec(Variation) });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'deleteCard' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getSavedCards' : IDL.Func([], [IDL.Vec(SavedCard)], ['query']),
    'saveCard' : IDL.Func([CardInput], [IDL.Text], []),
    'solveQuestion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [SolverResult],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };