/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnswerOption {
  'text' : string,
  'isCorrect' : boolean,
  'letter' : string,
}
export type CardId = string;
export interface CardInput {
  'variationQuestion' : string,
  'question' : string,
  'answerOptions' : Array<AnswerOption>,
  'steps' : Array<SolutionStep>,
  'confidence' : bigint,
}
export interface SavedCard {
  'id' : CardId,
  'variationQuestion' : string,
  'question' : string,
  'answerOptions' : Array<AnswerOption>,
  'steps' : Array<SolutionStep>,
  'savedAt' : Timestamp,
  'confidence' : bigint,
}
export interface SolutionStep {
  'result' : string,
  'description' : string,
  'stepNumber' : bigint,
  'formula' : string,
}
export interface SolverResult { 'variations' : Array<Variation> }
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface Variation {
  'id' : string,
  'question' : string,
  'correctAnswer' : string,
  'answerOptions' : Array<AnswerOption>,
  'distractors' : Array<string>,
  'steps' : Array<SolutionStep>,
  'confidence' : bigint,
  'warningFlag' : boolean,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'deleteCard' : ActorMethod<[string], boolean>,
  'getSavedCards' : ActorMethod<[], Array<SavedCard>>,
  'saveCard' : ActorMethod<[CardInput], string>,
  'solveQuestion' : ActorMethod<[string, string, bigint, bigint], SolverResult>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];